version: '3.8'

services:
  app:
    build:
      context: ./ShoppingAPI
    container_name: shopping_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - shopping_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: '<give any database name>'
      MYSQL_USER: '<give any username>'
      MYSQL_PASSWORD: '<give any password>'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shopping_network

networks:
  shopping_network:
    driver: bridge

volumes:
  db_data:
